services:
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    command: >
      sh -c "rabbitmq-plugins enable rabbitmq_management && rabbitmq-server"

  celery_worker:
    build:
      context: .
      dockerfile: dockerfile_celery
    command: >
      bash -c "celery -A app.celery_tasks.celery_worker worker | celery -A app.celery_tasks.celery_worker flower"
    environment:
      - C_FORCE_ROOT=true
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  task-mgmt-sys:
    build:
      context: .
      dockerfile: dockerfile_fastapi
    container_name: task-mgmt-sys
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: >
      bash -c "alembic upgrade head | uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
    depends_on:
      - rabbitmq
      - redis
      - postgres_db

  postgres_db:
    image: postgres:16
    container_name: postgres
    volumes:
      - postgres_db:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres_db: